package com.ajailani.musicplayer.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF245FA6)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFD5E3FF)
val light_onPrimaryContainer = Color(0xFF001B3C)
val light_secondary = Color(0xFF555F71)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD9E3F8)
val light_onSecondaryContainer = Color(0xFF121C2B)
val light_tertiary = Color(0xFF6E5676)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFF8D8FE)
val light_onTertiaryContainer = Color(0xFF28132F)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFDFBFF)
val light_onBackground = Color(0xFF1A1C1E)
val light_surface = Color(0xFFFDFBFF)
val light_onSurface = Color(0xFF1A1C1E)
val light_surfaceVariant = Color(0xFFE0E2EC)
val light_onSurfaceVariant = Color(0xFF43474E)
val light_outline = Color(0xFF74777F)
val light_inverseOnSurface = Color(0xFFF1F0F4)
val light_inverseSurface = Color(0xFF2F3033)
val light_inversePrimary = Color(0xFFA7C8FF)
val light_surfaceTint = Color(0xFF245FA6)
val light_outlineVariant = Color(0xFFC4C6CF)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFA7C8FF)
val dark_onPrimary = Color(0xFF003061)
val dark_primaryContainer = Color(0xFF004689)
val dark_onPrimaryContainer = Color(0xFFD5E3FF)
val dark_secondary = Color(0xFFBDC7DC)
val dark_onSecondary = Color(0xFF273141)
val dark_secondaryContainer = Color(0xFF3D4758)
val dark_onSecondaryContainer = Color(0xFFD9E3F8)
val dark_tertiary = Color(0xFFDBBCE1)
val dark_onTertiary = Color(0xFF3E2845)
val dark_tertiaryContainer = Color(0xFF563E5D)
val dark_onTertiaryContainer = Color(0xFFF8D8FE)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1A1C1E)
val dark_onBackground = Color(0xFFE3E2E6)
val dark_surface = Color(0xFF1A1C1E)
val dark_onSurface = Color(0xFFE3E2E6)
val dark_surfaceVariant = Color(0xFF43474E)
val dark_onSurfaceVariant = Color(0xFFC4C6CF)
val dark_outline = Color(0xFF8E9199)
val dark_inverseOnSurface = Color(0xFF1A1C1E)
val dark_inverseSurface = Color(0xFFE3E2E6)
val dark_inversePrimary = Color(0xFF245FA6)
val dark_surfaceTint = Color(0xFFA7C8FF)
val dark_outlineVariant = Color(0xFF43474E)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF497DC6)